### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by allvespedia** [instabotai/instabotai#54]
I am extremely excited to test this bot, but I am encountering this error below all the time. I apologize for being new to this, but I would like some help to be able to use it without errors. Appreciate.

C:\Windows\system32>cd C:\Users\pc\AppData\Local\Programs\Python\Python37\instab
otai

C:\Users\pc\AppData\Local\Programs\Python\Python37\instabotai>python run.py -u username -p password
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_help
er
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242
, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342
, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from mtcnn.mtcnn import MTCNN
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\mtc
nn\mtcnn.py", line 38, in <module>
    import tensorflow as tf
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\importlib\__init_
_.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\site-packages\ten
sorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_help
er
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242
, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342
, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

C:\Users\pc\AppData\Local\Programs\Python\Python37\instabotai>

**Comment by reliefs** [comment]
I found this answer I hope this helps.
 I still found no documentation on what is that error number, but found that the newest Tensorflow requires AVX2 support from the CPU, and I have an i7 920, which doesn't support AVX, so I found a compilation for tensorflow without AVX, from https://github.com/fo40225/tensorflow-windows-wheel

https://devtalk.nvidia.com/default/topic/1057009/error-code-3221225501-when-trying-to-run-tensorflow/

**Comment by reliefs** [comment]
https://github.com/tintinmovie/Guides_and_Solutions/blob/master/Tensorflow%20-%20No%20module%20named%20'_pywrap_tensorflow_internal'.md
